ARG CORE_BASE=superlily/core:pre-ablation-20260912
FROM ${CORE_BASE}
USER 0
COPY apps/core/src/superlily_core/service.py apps/core/src/superlily_core/routes.py apps/core/src/superlily_core/settings.py /usr/local/lib/python3.13/site-packages/superlily_core/
RUN chmod -R a+rX /usr/local/lib/python3.13/site-packages/superlily_core
USER 65532:65532
